#!/bin/sh
set -e

# Unstaged local changes?
if ! git diff --no-ext-diff --ignore-submodules --quiet --exit-code; then
    exit 1
else
    # Staged local changes?
    if ! git diff-index --cached --quiet --ignore-submodules --exit-code HEAD --; then
        exit 2
    else
        exit 0
    fi
fi
