#!/bin/sh
set -e

usage () {
    echo "usage: git is-merged-into <subject> <into-base>" >&2
    echo >&2
    echo "Will return with an exit code of 0 or 1." >&2
}

if [ $# -eq 2 ]; then
    subject=$1
    base=$2
else
    usage
    exit 2
fi

subject_sha=$(git sha "$subject")
ancestor_sha=$(git merge-base "$subject" "$base")
[ "$ancestor_sha" = "$subject_sha" ]
