#!/bin/sh
set -e

usage () {
    echo "usage: git change-user <wrong-email> <new-email> <new-name>" >&2
    echo >&2
    echo "Will return with an exit code of 2." >&2
}

if [ $# -eq 3 ]; then
    wrong_email=$1
    new_email=$2
    new_name=$3
else
    usage
    exit 2
fi

git filter-branch --env-filter '
WRONG_EMAIL=$wrong_email
NEW_NAME=$new_name
NEW_EMAIL=$new_email

if [ "$GIT_COMMITTER_EMAIL" = "$WRONG_EMAIL" ]
then
    export GIT_COMMITTER_NAME="$NEW_NAME"
    export GIT_COMMITTER_EMAIL="$NEW_EMAIL"
fi
if [ "$GIT_AUTHOR_EMAIL" = "$WRONG_EMAIL" ]
then
    export GIT_AUTHOR_NAME="$NEW_NAME"
    export GIT_AUTHOR_EMAIL="$NEW_EMAIL"
fi
' --tag-name-filter cat -- --branches --tags
