#!/bin/sh
set -e

usage () {
    cat <<'EOF'
usage: git tag-exists <tag>

Will return with an exit code of 0 or 1.
EOF
}

if [ $# -eq 1 ]; then
    tag=$1
else
    usage >&2
    exit 2
fi

git show-ref --tags --quiet --verify -- "refs/tags/$tag"
