#!/bin/sh
set -e

usage () {
    echo "usage: git conflicts [-qh]" >&2
    echo >&2
    echo "Compares merge outcomes against all local branches and display " >&2
    echo "whether a merge would cause merge conflicts." >&2
    echo >&2
    echo "Options:" >&2
    echo "-q    Be quiet (only report about conflicts)" >&2
    echo "-h    Show this help" >&2
}

quiet=0
while getopts qh flag; do
    case "$flag" in
        q) quiet=1;;
        h) usage; exit 2;;
    esac
done
shift $(($OPTIND - 1))

if git is-dirty; then
    echo "Can't check when you have local changes." >&2
    exit 2
fi

for branch in $(git local-branches); do
    if git merges-cleanly "$branch"; then
        if [ $quiet -eq 0 ]; then
            echo "$branch... merges cleanly"
        fi
    else
        echo "$branch... CONFLICTS AHEAD"
    fi
done
