#!/bin/sh
set -e

usage () {
    cat <<'EOF'
usage: git last-commit-to-file [-h] <file> [<file> ...]

Returns the SHA of the commit that last touched the given file.
If multiple files are given, will return the SHA that most-recently
changed _any_ of the files.

Options:
-h    Show this help
EOF
}

while getopts h flag; do
    case "$flag" in
        h) usage; exit 0;;
    esac
done
shift $(($OPTIND - 1))

if [ $# -lt 1 ]; then
    usage >&2
    exit 2
fi

git log -1 --format='%H' -- "$@" 2>/dev/null
