#!/bin/sh
set -e

root="$(git root)"
realpath='realpath'

# use 'grealpath' from GNU coreutils if it exists on macOS/BSD
if type grealpath >/dev/null 2>&1; then
    realpath='grealpath'
fi

# if 'realpath' isn't available, or isn't the GNU version...
if ! $realpath --version 2>/dev/null | grep -q GNU; then
    echo "GNU coreutils 'realpath' is required" >&2
    exit 2
fi

# read filenames as arguments if stdin is a terminal (not a pipe)
if [ -t 0 ]; then
    while [ $# -gt 0 ]; do
        $realpath --relative-to=. "$root/$1"
        shift
    done
else
    # otherwise read linewise from stdin (preserving any \'s and whitespace)
    while IFS= read -r f; do
        $realpath --relative-to=. "$root/$f"
    done
fi
