#!/bin/sh
set -eu

# TODO: Make the max age configurable

( git local-branches; git remote-branches ) | while read branch; do
    maybebranch=$(git log -1 --since=3.weeks.ago -s $branch)
    [ -n "$maybebranch" ] && echo "$branch"
done
