#!/bin/sh
set -e

usage () {
    cat <<'EOF'
usage: git remote-branch-exists [<remote>] <branch>

Will return with an exit code of 0 or 1.
EOF
}

if [ $# -eq 1 ]; then
    remote=origin
    branch=$1
elif [ $# -eq 2 ]; then
    remote=$1
    branch=$2
else
    usage >&2
    exit 2
fi

git show-ref --quiet --verify -- "refs/remotes/$remote/$branch"
