#!/bin/sh
set -e
    
usage () {
    echo "usage: git recent-branches [-h]" >&2
    echo >&2
    echo "Shows a list of branches that have been modified since the specified date range. Defaults to '1.week.ago'." >&2
    echo >&2
    echo "Options:" >&2
    echo "-h    Show this help" >&2
}

while getopts h flag; do
    case "$flag" in
        h) usage; exit 2;;
    esac
done

git for-each-ref --count=30 --sort=-committerdate refs/heads/ --format='%(refname:short)'
