#!/bin/sh
set -eu

probe_symbolic_ref() {
    local symbolic_ref_main=$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | cut -d'/' -f4)
    if [ -n "$symbolic_ref_main" ]; then
        echo $symbolic_ref_main
        exit 0
    fi
}

probe_symbolic_ref

for probe in main mainline production master; do
    if git local-branch-exists "$probe"; then
        echo "$probe"
        exit 0
    fi
done

# Make an expensive network call to set this
if git remote set-head origin --auto 2>/dev/null; then
    probe_symbolic_ref
fi

echo "No main branch found" >&2
exit 2
