#!/bin/sh
set -e

usage () {
    cat <<'EOF'
usage: git conflicts [-rqh]

Compares merge outcomes against all local branches and display
whether a merge would cause merge conflicts.

Options:
-r    Remote branches (default is only local branches)
-q    Be quiet (only report about conflicts)
-h    Show this help
EOF
}

quiet=0
remotes=0
while getopts rqh flag; do
    case "$flag" in
        r) remotes=1;;
        q) quiet=1;;
        h) usage; exit 0;;
    esac
done
shift $(($OPTIND - 1))

if git is-dirty; then
    echo "Can't check when you have local changes." >&2
    exit 2
fi

if [ "$remotes" -eq 1 ]; then
    branches="$(git remote-branches)"
else
    branches="$(git local-branches)"
fi
for branch in $branches; do
    if git merges-cleanly "$branch"; then
        if [ $quiet -eq 0 ]; then
            echo "$branch... merges cleanly"
        fi
    else
        echo "$branch... CONFLICTS AHEAD"
    fi
done
