#!/bin/sh
set -e
    
usage () {
    echo "usage: git recent-branches [-h] [<date-range>]" >&2
    echo >&2
    echo "Shows a list of branches that have been modified since the specified date range. Defaults to '1.week.ago'." >&2
    echo >&2
    echo "Options:" >&2
    echo "-h    Show this help" >&2
}

while getopts h flag; do
    case "$flag" in
        h) usage; exit 2;;
    esac
done
shift $(($OPTIND - 1))

fail_if_empty () {
    empty=1
    while read line; do
        echo "$line"
        empty=0
    done
    test $empty -eq 0
}

daterange=${1-1.week.ago}
for branch in $(git local-branches); do
    if git log -1 "--pretty=%H" "--since=$daterange" "$branch" | fail_if_empty >/dev/null; then
        echo "$branch"
    fi
done
