#!/bin/sh
set -e

# Ensure we have a clean working tree
git is-clean -v

ORIG_SHA="$(git sha HEAD)"
echo "Original commit is: $ORIG_SHA"

LAST_COMMIT_MSG="$(git log --pretty='%s' -1)"
git delouse
git diff --name-only --relative | while read f; do
  git commit --no-verify -C "$ORIG_SHA" -- "$f"
  git commit --amend --no-verify -m "$LAST_COMMIT_MSG @ $f"
done

echo "Success! Original commit was: $ORIG_SHA"
