#!/bin/sh
set -e

usage () {
    echo "usage: git cleanup-squashed [-nl]" >&2
    echo >&2
    echo "Deletes all branches that have already been squash-merged into master." >&2
    echo >&2
    echo "Options:" >&2
    echo "-n    Dry-run" >&2
    echo "-h    Show this help" >&2
}

dryrun=0
while getopts nlh flag; do
      case "$flag" in
          n) dryrun=1;;
          h) usage; exit 2;;
      esac
done
shift $(($OPTIND - 1))

#
# This will clean up any local branch that has been merged into any of
# the known "trunks". Trunks are any of:
#
#   - master (local) + origin/master
#

safegit() {
    if [ "$dryrun" -eq 1 ]; then
        echo git "$@"
    else
        git "$@"
    fi
}

#
# The Algorithm[tm]
# - Create a temporary dangling squashed commit with git commit-tree
# - Then use git cherry to check if the squashed commit has already been applied to master
# - If it has, then delete the branch
#

git for-each-ref refs/heads/ "--format=%(refname:short)" | while read branch; do
    # Skip if master branch
    if [ $branch = "master" ]; then
        continue
    fi

    # Find the merge base for this branch
    merge_base=$(git merge-base master $branch)

    # Get the tree object of the branch
    branch_tree="$(git rev-parse $branch^{tree})"

    # Create a squashed commit object of the branch tree with parent
    # of $merge_base with a commit message of "_"
    dangling_squashed_commit="$(git commit-tree $branch_tree -p $merge_base -m _)"

    # Show a summary of what has yet to be applied
    cherry_commit="$(git cherry master $dangling_squashed_commit)"

    if [ "$cherry_commit" = "- $dangling_squashed_commit" ]; then
        # If "- <commit-sha>", (ex. - "- 851cb44727") this means the
        # commit is in master and can be dropped if you rebased
        # against master
        safegit branch -D $branch
    else
        # If "+ <commit-sha>", (ex. - "+ 851cb44727") this means the
        # commit still needs to be kept so that it will be applied to
        # master
        echo "Branch $branch is not fully merged, Skipping..."
    fi
done
