#!/bin/sh
set -e

usage () {
    echo "usage: git modified [-iqh] <branch>" >&2
    echo >&2
    echo "Prints list of files that are locally modified (and exist).  The index is not " >&2
    echo "considered, unless the -i flag is provided." >&2
    echo >&2
    echo "This script is ideal for passing all locally modified files into your editor, like:" >&2
    echo '    $ vim `git modified`' >&2
    echo >&2
    echo "Options:" >&2
    echo "-i    Consider the index, too" >&2
    echo "-q    Be quiet, only return with 0 exit code when files are modified" >&2
    echo "-h    Show this help" >&2
}

index=0
quiet=0
while getopts iqh flag; do
    case "$flag" in
        i) index=1;;
        q) quiet=1;;
        h) usage; exit 2;;
    esac
done
shift $(($OPTIND - 1))

# X          Y     Meaning
# -------------------------------------------------
#           [MD]   not updated
# M        [ MD]   updated in index
# A        [ MD]   added to index
# D         [ M]   deleted from index
# R        [ MD]   renamed in index
# C        [ MD]   copied in index
# [MARC]           index and work tree matches
# [ MARC]     M    work tree changed since index
# [ MARC]     D    deleted in work tree
# -------------------------------------------------
# D           D    unmerged, both deleted
# A           U    unmerged, added by us
# U           D    unmerged, deleted by them
# U           A    unmerged, added by them
# D           U    unmerged, deleted by us
# A           A    unmerged, both added
# U           U    unmerged, both modified
# -------------------------------------------------
# ?           ?    untracked
# !           !    ignored
# -------------------------------------------------

status () {
    git status --porcelain | grep -vEe '^.D' | grep -vEe '^D '
}

fix_rename_notation () {
    sed -Ee 's/.* -> (.*)/\1/'
}

modified_in_index () {
    status | colrm 1 3 | fix_rename_notation
}

modified_locally () {
    status | colrm 1 1 | grep -vEe '^[ ]' | colrm 1 2 | fix_rename_notation
}

fail_if_empty () {
    empty=1
    while read line; do
        if [ $quiet -eq 0 ]; then
            echo "$line"
        fi
        empty=0
    done
    test $empty -eq 0
}

if [ $index -eq 1 ]; then
    modified_in_index | fail_if_empty
else
    modified_locally | fail_if_empty
fi
